id: P003127
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21841
  title: མངོན་བརྗོད་ཉེར་མཁོ་གཅེས་བཏུས་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  volumes:
    511e452ca80a44139c0b18c96daf796b:
      image_group_id: I1KG22015
      title: ''
      volume_number: 1
      total_pages: 248
