id: P003127
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:08.204851
source_metadata:
  id: bdr:W1KG21841
  title: མངོན་བརྗོད་ཉེར་མཁོ་གཅེས་བཏུས་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  volumes:
    511e452ca80a44139c0b18c96daf796b:
      image_group_id: I1KG22015
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
